version: "3.3"
services:
  nextjs:
    ports:
      - 3000:3000
    image: mrhealer1207/wecheck999:latest
    build:
      context: ./
      dockerfile: Dockerfile
    environment: 
      - BASE_URL=$${BASE_URL}
    volumes:
      - ./packages/wecheck:/app
      - /app/.next